version: '3.8'

services:
  migration:
    build: .
    command: alembic upgrade head
    env_file:
      - .env
    
  fastapi:
    build: .
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - migration
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # celery:
  #   build: .
  #   volumes:
  #     - ./src:/app/src
  #   env_file:
  #     - .env
  #   command: celery -A src.celery_worker worker -B --loglevel=info 
  #   depends_on:
  #     - redis

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi