version: '3.8'

services:
  migration:
    build: .
    volumes:
      - ./src:/app/src
    command: alembic upgrade head
    env_file:
      - .env
    
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - migration

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi