name: Deploy on AWS

on:
  push:
    branches:
      - 'main'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip the files
        run: |
          zip -r app.zip ./app

      - name: Upload to S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./app.zip
          destination: s3://${{ secrets.S3_BUCKET }}/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.S3_BUCKET_REGION }}
              
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo rm -rf ~/app
            mkdir ~/app
            aws s3 cp s3://${{ secrets.S3_BUCKET }}/app.zip ~/app
            cd app
            unzip app.zip
            rm app.zip
            docker-compose up -d --build
